### ISSUE TITLE
Implement natural-sounding strumming

### ISSUE THREAD

**Issue by emilis-wix** [emilis/summer-bandits#3]
Guitar should be able to

- strum up and down
- map chords to actual guitar strings
- subtly vary timings and velocities to sound natural
- take into account energy and tension levels from conductor

**Comment by emilis-wix** [comment]
- WebMidi `Note` class has the option for duration.
- The interval between strings that worked well at the meeting was ~50ms.

**Comment by laurynaslubys** [comment]
TODO from #13 :

- [ ] Send note off messages
- [ ] Review chord change approach, especially wrt follower mode.

**Comment by emilis-wix** [comment]
I think it's done.
